{"abstract":[{"text":"The client callback.","type":"text"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"symbolKind":"property","title":"clientCallback","externalID":"c:objc(cs)MBMCustomRasterSourceOptions(py)clientCallback","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientCallback","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","text":"CustomRasterSourceClient","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"clientCallback"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientCallback","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","text":"CustomRasterSourceClient","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Custom raster sourtce can be configured for either direct or asynchronous rendering:"},{"text":" ","type":"text"},{"type":"text","text":"When "},{"code":"CustomRasterSourceTileStatusChangedCallback","type":"codeVoice"},{"text":" instance is provided, rendering is asynchronous, and","type":"text"},{"text":" ","type":"text"},{"text":"the client should use setStyleCustomRasterSourceTileData() API to provide the tile data.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"When ","type":"text"},{"code":"CustomRasterSourceTileRenderer","type":"codeVoice"},{"text":" instance is provided, rendering is direct, and the client should","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"render to the tile from within the "},{"type":"codeVoice","code":"CustomRasterSourceTileRenderer.renderToTile()"},{"type":"text","text":" method."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions"]]},"identifier":{"url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/clientCallback","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions\/clientcallback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/customrastersourceoptions\/clientcallback"]}],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"role":"collection","kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"abstract":[],"kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/sources","title":"Sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions/clientCallback":{"title":"clientCallback","kind":"symbol","abstract":[{"type":"text","text":"The client callback."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions\/clientCallback","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientCallback","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient","text":"CustomRasterSourceClient"}],"navigatorTitle":[{"kind":"identifier","text":"clientCallback"}],"url":"\/documentation\/mapboxmaps\/customrastersourceoptions\/clientcallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","url":"\/documentation\/mapboxmaps\/customrastersourceclient","title":"CustomRasterSourceClient","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceClient","kind":"identifier"}],"navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"abstract":[{"type":"text","text":"Options for custom raster source."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","title":"CustomRasterSourceOptions","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"clientCallback","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"clientCallback","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MBMCustomRasterSourceClient","kind":"typeIdentifier","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceClient"},{"kind":"text","text":" * "},{"text":"clientCallback","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"clientCallback","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1clientCallback\/title"},{"op":"replace","value":[{"text":"clientCallback","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions~1clientCallback\/fragments"},{"value":"MBMCustomRasterSourceClient","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle","value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace"},{"value":"MBMCustomRasterSourceOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceOptions","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle"}]}]}