{"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain"]]},"variants":[{"paths":["\/documentation\/mapboxcommon\/tiledatadomain\/adas"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mapboxcommon\/tiledatadomain\/adas"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"adas","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adas"}],"roleHeading":"Case","title":"TileDataDomain.adas","role":"symbol","navigatorTitle":[{"text":"MBXTileDataDomainAdas","kind":"identifier"}],"modules":[{"name":"MapboxCommon"}],"symbolKind":"case","externalID":"c:@E@MBXTileDataDomain@MBXTileDataDomainAdas"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain\/adas"},"kind":"symbol","sections":[],"abstract":[{"text":"Data for ADAS.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileStore-APIs":{"url":"\/documentation\/mapboxmaps\/tilestore-apis","kind":"article","title":"TileStore APIs","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileStore-APIs"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain":{"abstract":[{"type":"text","text":"Describes the tiles data domain."}],"navigatorTitle":[{"text":"TileDataDomain","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TileDataDomain","kind":"identifier"}],"title":"TileDataDomain","url":"\/documentation\/mapboxcommon\/tiledatadomain","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain","role":"symbol","kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/TileDataDomain/adas":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/TileDataDomain\/adas","kind":"symbol","title":"TileDataDomain.adas","abstract":[{"type":"text","text":"Data for ADAS."}],"type":"topic","url":"\/documentation\/mapboxcommon\/tiledatadomain\/adas","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"adas"}],"navigatorTitle":[{"text":"MBXTileDataDomainAdas","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"role":"collection","kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MBXTileDataDomainAdas","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MBXTileDataDomainAdas"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MBXTileDataDomainAdas","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"MBXTileDataDomain","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/fragments","value":[{"kind":"identifier","text":"MBXTileDataDomain"}]},{"op":"replace","value":[{"kind":"identifier","text":"MBXTileDataDomain"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain~1adas\/title","value":"MBXTileDataDomainAdas","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1TileDataDomain~1adas\/fragments","value":[{"kind":"identifier","text":"MBXTileDataDomainAdas"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}