{"metadata":{"role":"symbol","modules":[{"name":"MapboxCommon"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:objc(cs)MBXHttpRequest(py)timeout","title":"timeout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timeout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"}],"navigatorTitle":[{"text":"timeout","kind":"identifier"}]},"abstract":[{"text":"Timeout defines how long, in seconds, the request is allowed to take in total (including connecting to the host).","type":"text"},{"text":" ","type":"text"},{"text":"Default is 0, meaning no timeout.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"timeout","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mapboxcommon\/httprequest\/timeout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxcommon\/httprequest\/timeout"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/timeout"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"role":"collection","kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest/timeout":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt64","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt64V"}],"navigatorTitle":[{"text":"timeout","kind":"identifier"}],"abstract":[{"type":"text","text":"Timeout defines how long, in seconds, the request is allowed to take in total (including connecting to the host)."},{"type":"text","text":" "},{"type":"text","text":"Default is 0, meaning no timeout."}],"url":"\/documentation\/mapboxcommon\/httprequest\/timeout","kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest\/timeout","title":"timeout","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon/HttpRequest":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HttpRequest"}],"navigatorTitle":[{"text":"HttpRequest","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon\/HttpRequest","url":"\/documentation\/mapboxcommon\/httprequest","title":"HttpRequest","abstract":[{"text":"HttpRequest holds basic information for construction of an HTTP request","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxCommon":{"url":"\/documentation\/mapboxcommon","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxCommon","type":"topic","title":"MapboxCommon"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"timeout","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"timeout"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@uint64_t","text":"uint64_t","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"timeout","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1timeout\/title","value":"timeout"},{"value":[{"kind":"identifier","text":"timeout"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest~1timeout\/fragments"},{"op":"replace","value":"MBXHttpRequest","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/title"},{"op":"replace","value":[{"text":"MBXHttpRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxCommon~1HttpRequest\/navigatorTitle","value":[{"text":"MBXHttpRequest","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}