{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/pixelRatio"},"metadata":{"platforms":[],"title":"pixelRatio","roleHeading":"Instance Property","modules":[{"name":"MapboxMaps"}],"role":"symbol","externalID":"c:objc(cs)MBMOfflineRegionGeometryDefinition(py)pixelRatio","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pixelRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"pixelRatio"}],"symbolKind":"property"},"abstract":[{"type":"text","text":"Pixel ratio to be accounted for when downloading assets"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pixelRatio","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/pixelratio"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/pixelratio"]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition"]]},"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition/pixelRatio":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition\/pixelRatio","abstract":[{"type":"text","text":"Pixel ratio to be accounted for when downloading assets"}],"deprecated":true,"kind":"symbol","title":"pixelRatio","url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition\/pixelratio","role":"symbol","navigatorTitle":[{"text":"pixelRatio","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pixelRatio","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Offline":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Offline","abstract":[],"type":"topic","url":"\/documentation\/mapboxmaps\/offline","kind":"article","title":"Offline Support","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CoreMaps":{"kind":"article","abstract":[{"text":"Maps rendering SDK also known as GL-Native","type":"text"}],"title":"Core Maps API","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CoreMaps","type":"topic","url":"\/documentation\/mapboxmaps\/coremaps","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"role":"collection","kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/OfflineRegionGeometryDefinition":{"abstract":[{"type":"text","text":"An offline region definition is a geographic region defined by a style URL,"},{"type":"text","text":" "},{"text":"a geometry, zoom range, and device pixel ratio. Both ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"maxZoom"},{"text":" must be ≥ 0,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and "},{"code":"maxZoom","type":"codeVoice"},{"text":" must be ≥ ","type":"text"},{"type":"codeVoice","code":"minZoom"},{"type":"text","text":". The "},{"code":"maxZoom","type":"codeVoice"},{"text":" may be ∞, in which case for each tile source,","type":"text"},{"text":" ","type":"text"},{"text":"the region will include tiles from ","type":"text"},{"code":"minZoom","type":"codeVoice"},{"type":"text","text":" up to the maximum zoom level provided by that source."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"pixelRatio"},{"type":"text","text":" must be ≥ 0 and should typically be 1.0 or 2.0."}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/OfflineRegionGeometryDefinition","navigatorTitle":[{"text":"OfflineRegionGeometryDefinition","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OfflineRegionGeometryDefinition"}],"kind":"symbol","title":"OfflineRegionGeometryDefinition","role":"symbol","type":"topic","url":"\/documentation\/mapboxmaps\/offlineregiongeometrydefinition"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"pixelRatio","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pixelRatio"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"pixelRatio","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1pixelRatio\/title","value":"pixelRatio"},{"value":[{"text":"pixelRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition~1pixelRatio\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/title","value":"MBMOfflineRegionGeometryDefinition"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/fragments","value":[{"text":"MBMOfflineRegionGeometryDefinition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1OfflineRegionGeometryDefinition\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMOfflineRegionGeometryDefinition"}]}]}]}