{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSource"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"To add the data, set options with a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","isActive":true},{"type":"text","text":" with a fetchTileFunction callback"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize"],"anchor":"Sources","generated":true,"title":"Sources"}],"variants":[{"paths":["\/documentation\/mapboxmaps\/customrastersource"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"]]},"metadata":{"externalID":"s:10MapboxMaps18CustomRasterSourceV","role":"symbol","tags":[{"type":"spi","text":"SPI"}],"modules":[{"name":"MapboxMaps"}],"roleHeading":"Structure","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}],"symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSource"}],"title":"CustomRasterSource"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/init(id:options:maxOverscaleFactorForParentTiles:)"],"title":"Initializers","anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/id","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/maxOverscaleFactorForParentTiles","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/options","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/type"],"anchor":"Instance-Properties","generated":true},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/Equatable-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/Source-Implementations","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/StyleEncodable-Implementations"]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable","doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable","doc:\/\/com.mapbox.MapboxMaps\/Se","doc:\/\/com.mapbox.MapboxMaps\/SE","doc:\/\/com.mapbox.MapboxMaps\/SQ"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"references":{"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/maxOverscaleFactorForParentTiles":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/maxOverscaleFactorForParentTiles","abstract":[{"text":"When a set of tiles for a current zoom level is being rendered and some of the ideal tiles that cover the screen are not yet loaded, parent tiles could be used instead. Note that this might introduce unwanted rendering side-effects, especially for raster tiles that are overscaled multiple times. This property sets the maximum limit for how much a parent tile can be overscaled.","type":"text"}],"type":"topic","title":"maxOverscaleFactorForParentTiles","url":"\/documentation\/mapboxmaps\/customrastersource\/maxoverscalefactorforparenttiles","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxOverscaleFactorForParentTiles","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":"?","kind":"text"}],"tags":[{"type":"spi","text":"SPI"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileFunctionCallback":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"TileFunctionCallback","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/tilefunctioncallback","abstract":[{"text":"Callback to do various operations for tile.","type":"text"},{"text":" ","type":"text"},{"text":"For example, fetching a tile or cancelling a tile request.","type":"text"}],"navigatorTitle":[{"text":"TileFunctionCallback","kind":"identifier"}],"type":"topic","title":"TileFunctionCallback","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileFunctionCallback"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileData":{"abstract":[{"text":"Data for a specific CustomRasterSource tile.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomRasterSourceTileData","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourcetiledata","title":"CustomRasterSourceTileData","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileData"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/id":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/id","kind":"symbol","title":"id","type":"topic","abstract":[{"type":"text","text":"Style source identifier."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","tags":[{"type":"spi","text":"SPI"}],"url":"\/documentation\/mapboxmaps\/customrastersource\/id"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceType":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceType","url":"\/documentation\/mapboxmaps\/sourcetype","title":"SourceType","abstract":[{"type":"text","text":"Struct of supported Source Types"},{"text":" ","type":"text"},{"type":"text","text":"Docs : https:\/\/docs.mapbox.com\/mapbox-gl-js\/style-spec\/sources\/"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SourceType"}],"navigatorTitle":[{"text":"SourceType","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/VectorSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/VectorSource","url":"\/documentation\/mapboxmaps\/vectorsource","title":"VectorSource","abstract":[{"text":"A vector tile source.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VectorSource"}],"navigatorTitle":[{"text":"VectorSource","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/MapStyleContent":{"url":"\/documentation\/mapboxmaps\/mapstylecontent","role":"symbol","abstract":[{"text":"A protocol used to create any type of  map style content, such as layers, sources, lighting and others.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MapStyleContent","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/MapStyleContent","title":"MapStyleContent","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MapStyleContent","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/init(id:options:maxOverscaleFactorForParentTiles:)":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/init(id:options:maxOverscaleFactorForParentTiles:)","abstract":[],"type":"topic","title":"init(id:options:maxOverscaleFactorForParentTiles:)","url":"\/documentation\/mapboxmaps\/customrastersource\/init(id:options:maxoverscalefactorforparenttiles:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CustomRasterSourceOptions","preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxOverscaleFactorForParentTiles"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"tags":[{"text":"SPI","type":"spi"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleEncodable":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleEncodable","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styleencodable","abstract":[{"text":"A protocol describing a style-related entity that can be encoded.","type":"text"}],"navigatorTitle":[{"text":"StyleEncodable","kind":"identifier"}],"type":"topic","title":"StyleEncodable","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleEncodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterArraySource":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RasterArraySource","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/rasterarraysource","abstract":[{"type":"text","text":"A raster array source"}],"tags":[{"type":"spi","text":"SPI"}],"navigatorTitle":[{"kind":"identifier","text":"RasterArraySource"}],"type":"topic","title":"RasterArraySource","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterArraySource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Source":{"url":"\/documentation\/mapboxmaps\/source","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"Source","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Source","title":"Source","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Source","kind":"identifier"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/Source-Implementations":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/Source-Implementations","kind":"article","title":"Source Implementations","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/mapboxmaps\/customrastersource\/source-implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatusChangedCallback":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatusChangedCallback","url":"\/documentation\/mapboxmaps\/customrastersourcetilestatuschangedcallback","title":"CustomRasterSourceTileStatusChangedCallback","abstract":[{"type":"text","text":"Callback for changing a CustomRasterSource tile status."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"navigatorTitle":[{"text":"CustomRasterSourceTileStatusChangedCallback","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClientType":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClientType","title":"CustomRasterSourceClientType","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourceclienttype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomRasterSourceClientType"}],"abstract":[],"navigatorTitle":[{"text":"CustomRasterSourceClientType","kind":"identifier"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Sources":{"abstract":[],"kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/mapboxmaps\/sources","title":"Sources","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Sources"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/options":{"tags":[{"type":"spi","text":"SPI"}],"kind":"symbol","abstract":[{"text":"Settings for the custom raster source, including a fetchTileFunction callback","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"options","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MBMCustomRasterSourceOptions","text":"CustomRasterSourceOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/options","url":"\/documentation\/mapboxmaps\/customrastersource\/options","title":"options","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterSource":{"url":"\/documentation\/mapboxmaps\/rastersource","kind":"symbol","title":"RasterSource","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"RasterSource","kind":"identifier"}],"navigatorTitle":[{"text":"RasterSource","kind":"identifier"}],"abstract":[{"text":"A raster tile source.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceOptions":{"abstract":[{"type":"text","text":"Options for custom raster source."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/mapboxmaps\/customrastersourceoptions","title":"CustomRasterSourceOptions","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceOptions"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceOptions"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/type":{"role":"symbol","title":"type","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SourceType","preciseIdentifier":"s:10MapboxMaps10SourceTypeV","kind":"typeIdentifier"}],"tags":[{"text":"SPI","type":"spi"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/type","url":"\/documentation\/mapboxmaps\/customrastersource\/type","abstract":[{"text":"The Source type","type":"text"}]},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/StyleDecodable":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"StyleDecodable","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/styledecodable","abstract":[{"text":"A protocol describing a style-related entity that can be decoded.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"StyleDecodable"}],"type":"topic","title":"StyleDecodable","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/StyleDecodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSourceData":{"abstract":[{"type":"text","text":"Captures potential values of the "},{"type":"codeVoice","code":"data"},{"type":"text","text":" property of a GeoJSONSource."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GeoJSONSourceData"}],"type":"topic","url":"\/documentation\/mapboxmaps\/geojsonsourcedata","title":"GeoJSONSourceData","navigatorTitle":[{"text":"GeoJSONSourceData","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSourceData"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/RasterDemSource":{"abstract":[{"type":"text","text":"A RGB-encoded raster DEM source"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RasterDemSource"}],"type":"topic","url":"\/documentation\/mapboxmaps\/rasterdemsource","title":"RasterDemSource","navigatorTitle":[{"text":"RasterDemSource","kind":"identifier"}],"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/RasterDemSource"},"doc://com.mapbox.MapboxMaps/Se":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/Se","type":"unresolvable","title":"Swift.Decodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileStatus":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileStatus"}],"abstract":[{"type":"text","text":"CustomRasterSource tile status."}],"url":"\/documentation\/mapboxmaps\/customrastersourcetilestatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CustomRasterSourceTileStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileStatus","role":"symbol","title":"CustomRasterSourceTileStatus"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySource":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomGeometrySource","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customgeometrysource","abstract":[{"text":"Describes a Custom Geometry Source to be used in the style","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CustomGeometrySource"}],"type":"topic","title":"CustomGeometrySource","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomGeometrySourceOptions":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomGeometrySourceOptions","url":"\/documentation\/mapboxmaps\/customgeometrysourceoptions","title":"CustomGeometrySourceOptions","abstract":[{"text":"Options for custom geometry source.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"navigatorTitle":[{"text":"CustomGeometrySourceOptions","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/TileCacheBudgetSize":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/TileCacheBudgetSize","title":"TileCacheBudgetSize","role":"symbol","url":"\/documentation\/mapboxmaps\/tilecachebudgetsize","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TileCacheBudgetSize","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines a TileCacheBudgetSize, which can be set as either a megabyte or tile count limit."},{"type":"text","text":" "},{"type":"text","text":"Whenever tile cache goes over the defined limit"},{"type":"text","text":" "},{"text":"the least recently used tile will be evicted from the in-memory cache","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"TileCacheBudgetSize"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/GeoJSONSource":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/GeoJSONSource","title":"GeoJSONSource","role":"symbol","url":"\/documentation\/mapboxmaps\/geojsonsource","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"GeoJSONSource","kind":"identifier"}],"abstract":[{"text":"A GeoJSON data source.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GeoJSONSource"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/ImageSource":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/ImageSource","url":"\/documentation\/mapboxmaps\/imagesource","title":"ImageSource","abstract":[{"type":"text","text":"An image data source."}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSource","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSource"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/SourceInfo":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SourceInfo","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/sourceinfo","abstract":[{"text":"Information about a Source","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SourceInfo"}],"type":"topic","title":"SourceInfo","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/SourceInfo"},"doc://com.mapbox.MapboxMaps/SQ":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomRasterSource","kind":"identifier"}],"url":"\/documentation\/mapboxmaps\/customrastersource","abstract":[{"type":"text","text":"Describes a Custom Raster Source to be used in the style."}],"tags":[{"type":"spi","text":"SPI"}],"navigatorTitle":[{"text":"CustomRasterSource","kind":"identifier"}],"type":"topic","title":"CustomRasterSource","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/StyleEncodable-Implementations":{"url":"\/documentation\/mapboxmaps\/customrastersource\/styleencodable-implementations","kind":"article","title":"StyleEncodable Implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/StyleEncodable-Implementations"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps","role":"collection","url":"\/documentation\/mapboxmaps","kind":"symbol","title":"MapboxMaps","type":"topic","abstract":[{"type":"text","text":"Interactive, thoroughly customizable maps for iOS powered by vector tiles and Metal."}]},"doc://com.mapbox.MapboxMaps/documentation/Overview":{"url":"\/documentation\/overview","abstract":[],"role":"collection","kind":"article","title":"MapboxMaps Documentation","type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/Overview"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceClient":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceClient","url":"\/documentation\/mapboxmaps\/customrastersourceclient","title":"CustomRasterSourceClient","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomRasterSourceClient","kind":"identifier"}],"navigatorTitle":[{"text":"CustomRasterSourceClient","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSourceTileRenderer":{"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSourceTileRenderer","title":"CustomRasterSourceTileRenderer","role":"symbol","url":"\/documentation\/mapboxmaps\/customrastersourcetilerenderer","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"abstract":[{"text":"Interface for the direct rendering into the custom raster tiles.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CustomRasterSourceTileRenderer"}],"kind":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Scheme":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Scheme","url":"\/documentation\/mapboxmaps\/scheme","title":"Scheme","abstract":[{"text":"Influences the y direction of the tile coordinates. The global-mercator (aka Spherical Mercator) profile is assumed.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Scheme","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Scheme"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/CustomRasterSource/Equatable-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/CustomRasterSource\/Equatable-Implementations","url":"\/documentation\/mapboxmaps\/customrastersource\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/PromoteId":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/PromoteId","url":"\/documentation\/mapboxmaps\/promoteid","title":"PromoteId","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PromoteId","kind":"identifier"}],"navigatorTitle":[{"text":"PromoteId","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.mapbox.MapboxMaps/SE":{"identifier":"doc:\/\/com.mapbox.MapboxMaps\/SE","type":"unresolvable","title":"Swift.Encodable"},"doc://com.mapbox.MapboxMaps/documentation/MapboxMaps/Encoding":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Encoding"}],"url":"\/documentation\/mapboxmaps\/encoding","abstract":[{"text":"The encoding used by this source. Mapbox Terrain RGB is used by default","type":"text"}],"navigatorTitle":[{"text":"Encoding","kind":"identifier"}],"type":"topic","title":"Encoding","role":"symbol","identifier":"doc:\/\/com.mapbox.MapboxMaps\/documentation\/MapboxMaps\/Encoding"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MBMTileFunctionCallback","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/title"},{"value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1TileFunctionCallback\/navigatorTitle","value":[{"text":"MBMTileFunctionCallback","kind":"identifier"}]},{"value":"MBMCustomRasterSourceTileData","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileData\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/title","value":"MBMCustomRasterSourceTileStatusChangedCallback"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/fragments","op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatusChangedCallback","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatusChangedCallback\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileStatusChangedCallback"}]},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/title","op":"replace","value":"MBMCustomRasterSourceClientType"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/fragments","value":[{"text":"MBMCustomRasterSourceClientType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClientType\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClientType"}]},{"value":"MBMCustomRasterSourceOptions","op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}]},{"value":[{"kind":"identifier","text":"MBMCustomRasterSourceOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceOptions\/navigatorTitle"},{"op":"replace","value":"MBMCustomRasterSourceTileStatus","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/title"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/fragments","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/title","value":"MBMCustomGeometrySourceOptions","op":"replace"},{"value":[{"text":"MBMCustomGeometrySourceOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomGeometrySourceOptions\/navigatorTitle","value":[{"kind":"identifier","text":"MBMCustomGeometrySourceOptions"}]},{"value":"MBMCustomRasterSourceClient","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceClient"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/fragments"},{"value":[{"text":"MBMCustomRasterSourceClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceClient\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/title","value":"MBMCustomRasterSourceTileRenderer","op":"replace"},{"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/fragments","op":"replace","value":[{"kind":"identifier","text":"MBMCustomRasterSourceTileRenderer"}]},{"op":"replace","value":[{"text":"MBMCustomRasterSourceTileRenderer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.mapbox.MapboxMaps~1documentation~1MapboxMaps~1CustomRasterSourceTileRenderer\/navigatorTitle"}]}]}